"""Unit and Integration Tests for the Wishlist Decision Journey & Trigger Layer."""
import pytest
from database.db import get_db
from analysis.wishlist_journey import WishlistJourneyEngine
from analysis.opportunity import OpportunityEngine
from fastapi.testclient import TestClient
from dashboard.api import app


@pytest.fixture
def journey_engine():
    db = get_db()
    return WishlistJourneyEngine(db=db)


@pytest.fixture
def client():
    return TestClient(app)


def test_intent_metrics_strict_vs_broader(journey_engine):
    """Verify Strict Purchase Intent and Broader Commercial Intent mathematical consistency."""
    metrics = journey_engine.get_intent_metrics()
    
    assert "total_analyzed" in metrics
    assert "strict_purchase_intent_pct" in metrics
    assert "broader_commercial_intent_pct" in metrics
    assert "sanity_check_flagged" in metrics
    
    # Broader commercial intent must be >= Strict purchase intent
    assert metrics["broader_commercial_intent_pct"] >= metrics["strict_purchase_intent_pct"]
    assert metrics["total_analyzed"] > 0
    assert len(metrics["tiers"]) == 7


def test_why_users_save_distribution(journey_engine):
    """Verify Why Users Save decomposition contains canonical categories."""
    reasons = journey_engine.get_why_users_save()
    assert len(reasons) >= 7
    
    cat_keys = [r["category_key"] for r in reasons]
    assert "intentional_planning" in cat_keys
    assert "sale_price_waiting" in cat_keys
    assert "casual_bookmarking" in cat_keys
    assert "comparison" in cat_keys


def test_wishlist_states_funnel(journey_engine):
    """Verify 12-state decision funnel representation."""
    states = journey_engine.get_wishlist_states()
    assert len(states) == 12
    
    state_keys = [s["state_key"] for s in states]
    assert "just_saved" in state_keys
    assert "needs_information" in state_keys
    assert "waiting_for_price" in state_keys
    assert "purchased" in state_keys
    assert "abandoned" in state_keys


def test_purchase_triggers_grouping(journey_engine):
    """Verify triggers are segregated into Observed Stated, Potential, and Hypotheses."""
    triggers = journey_engine.get_purchase_triggers()
    assert "observed_stated" in triggers
    assert "potential_trigger" in triggers
    assert "hypothesis_to_validate" in triggers


def test_information_gaps_and_workarounds(journey_engine):
    """Verify info gaps and external workarounds matrix."""
    data = journey_engine.get_information_gaps_and_workarounds()
    assert "information_gaps" in data
    assert "external_workarounds" in data
    assert "gap_to_workaround_matrix" in data
    assert len(data["information_gaps"]) > 0


def test_opportunity_framework_structure():
    """Verify 8-part Opportunity Framework generated by OpportunityEngine."""
    db = get_db()
    opp_eng = OpportunityEngine(db=db)
    opps = opp_eng.prioritize_and_store_opportunities()
    
    assert len(opps) > 0
    top_opp = opps[0]
    
    # Check 8-part attributes
    assert "problem" in top_opp
    assert "observed_behaviour" in top_opp
    assert "evidence_frequency" in top_opp
    assert "purchase_relevance" in top_opp
    assert "potential_trigger" in top_opp
    assert "current_workaround" in top_opp
    assert "potential_opportunity" in top_opp
    assert "why_this_matters" in top_opp


def test_confidence_building_behaviours(journey_engine):
    """Verify empirical confidence building behaviours."""
    behaviours = journey_engine.get_confidence_building_behaviours()
    assert len(behaviours) >= 5
    assert behaviours[0]["pct"] > 0
    assert "Fit Confidence" in [b["category"] for b in behaviours]


def test_api_wishlist_endpoints(client):
    """Verify all FastAPI REST endpoints for the Wishlist Decision Journey."""
    # 1. Intent endpoint
    res = client.get("/api/wishlist/intent")
    assert res.status_code == 200
    assert "strict_purchase_intent_pct" in res.json()

    # 2. Save reasons endpoint
    res = client.get("/api/wishlist/save-reasons")
    assert res.status_code == 200
    assert isinstance(res.json(), list)

    # 3. States endpoint
    res = client.get("/api/wishlist/states")
    assert res.status_code == 200
    assert len(res.json()) == 12

    # 4. Triggers endpoint
    res = client.get("/api/wishlist/triggers")
    assert res.status_code == 200
    assert "observed_stated" in res.json()

    # 5. Gaps endpoint
    res = client.get("/api/wishlist/information-gaps")
    assert res.status_code == 200
    assert "information_gaps" in res.json()

    # 6. Confidence behaviours endpoint
    res = client.get("/api/wishlist/confidence-behaviours")
    assert res.status_code == 200
    assert isinstance(res.json(), list)
    assert len(res.json()) >= 5

